### ISSUE TITLE
Unable to close message This activity can no longer be participated in.

### ISSUE THREAD

**Issue by 21Gxme** [Nantawat6510545543/KU-ACTIVE#116]
<img width="1039" alt="image" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/113856957/4e7d2d29-7f70-4c09-83c6-a262615b4d47">
When I press participate repeatedly, a notification message will pop up. But I can only press one to make it disappear.

**Comment by CondricNay** [comment]
Error text box is now merged to a single block, so it can be closed now (hopefully)
