### ISSUE TITLE
Event's description in menu doesn't match user input. It seems to have .Title() for every words.

### ISSUE THREAD

**Issue by MeHappyLucky** [Nantawat6510545543/KU-ACTIVE#119]
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/f57c7253-e924-4410-854b-2100a8a3f0d3)
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/00322f02-6de3-48bf-8c3a-3395e56e0e61)

**Comment by CondricNay** [comment]
It's caused by text-transform tag is set to capitalize, we will fix it now

**Comment by CondricNay** [comment]
Fixed.
