### ISSUE TITLE
Can't create activity, Invalid date

### ISSUE THREAD

**Issue by Jwizzed** [Nantawat6510545543/KU-ACTIVE#120]
I am using safari and I can't create a new activity even I fill the `Publication Date` but it still give me "Enter a valid value".

<img width="613" alt="Screenshot 2566-11-23 at 23 47 28" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/101621268/69e61ffb-eed6-4537-a72b-3ee9f7b1fe4a">

**Comment by Nantawat6510545543** [comment]
Duplicate #107
