### ISSUE TITLE
Can't create activity

### ISSUE THREAD

**Issue by Peanutt47** [Nantawat6510545543/KU-ACTIVE#121]
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/85238329/0af4bb17-0ee8-4f3b-bd09-221cfae570e9)
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/85238329/20ebb0c9-9dea-4e66-9368-27e85d363727)
When I create an activity and attempt to input a number greater than 4 in the year field, I encounter a Server Error (500) after entering the number.

**Comment by CondricNay** [comment]
Fixed.

**Comment by CondricNay** [comment]
Should work now.
