### ISSUE TITLE
Encountered server 500 when creating new account with .

### ISSUE THREAD

**Issue by ChaiyawutTar** [Nantawat6510545543/KU-ACTIVE#124]
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114904790/727bfa5f-7c02-43b2-b105-6460738bfcde)

**Comment by CondricNay** [comment]
Can you explain more?

**Comment by Nantawat6510545543** [comment]
Due to the server's limited 4GB RAM capacity, delays may occur, possibly attributed to a high volume of requests. Regrettably, expanding the RAM is not feasible at the moment due to associated costs.
