### ISSUE TITLE
Create activity file input problem.

### ISSUE THREAD

**Issue by Qosanglesz** [Nantawat6510545543/KU-ACTIVE#125]
if i create activity and then i push some image file that not type of image file ex. docker.exe web will be error 502
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114909150/47bf83c4-62ea-4b1d-b5c9-8a039a3d2a9a)

**Comment by CondricNay** [comment]
i tried with ,pdf and .exe and .py file and it works properly. Can you maybe send me the file?

**Comment by Nantawat6510545543** [comment]
Can you tell me the size of the file?

**Comment by Qosanglesz** [comment]
about 2.08 Kb but i try to upload another file your app (update profile picture) already warning wrong file type. It ok it work correctly So I think may be it is the same problem like https://github.com/Nantawat6510545543/KU-ACTIVE/issues/121
(server error 500) when create new activity.

**Comment by Nantawat6510545543** [comment]
Due to the server's limited 4GB RAM capacity, delays may occur, possibly attributed to a high volume of requests. Regrettably, expanding the RAM is not feasible at the moment due to associated costs.
