### ISSUE TITLE
I can access the admin page

### ISSUE THREAD

**Issue by xNatthapol** [Nantawat6510545543/KU-ACTIVE#128]
<img width="1440" alt="image" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/115071646/f07b7765-2bfa-49c6-9177-4207c1dd9907">

**Comment by Nantawat6510545543** [comment]
In our demo it was mentioned that only users who have been appointed as admins can create and delete categories. If you are not there at the time, we recommend reading the "Use Case Diagram" in our [project proposal](https://docs.google.com/document/d/1fCbarHMIbQTxGYIbg5Lh2DMRRupwHXWj80ErWb67ScI/edit?usp=sharing).
Therefore, we have to open the admin page for easy access. Moreover, if you are an admin, we will also provide you with shortcut button.
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114897362/acea2f84-e8b6-4530-a46a-c1b431d8f72e)
