### ISSUE TITLE
I can't change the time when I want to create new activity.

### ISSUE THREAD

**Issue by 21Gxme** [Nantawat6510545543/KU-ACTIVE#132]
<img width="617" alt="image" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/113856957/b083ff2f-e83c-4755-9aa7-f30cc7618792">

**Comment by CondricNay** [comment]
What browser and OS type did you use to open this?

**Comment by 21Gxme** [comment]
MacOs Safari

**Comment by CondricNay** [comment]
https://caniuse.com/?search=date

For Firefox and Safari browser, datetime-local is only partially supported.
Meaning that you can only search by date, but not time.

**Comment by Nantawat6510545543** [comment]
Duplicate #107
