### ISSUE TITLE
In the dropdown navbar, it shows menus that should be authenticated

### ISSUE THREAD

**Issue by J-Jullaphong** [Nantawat6510545543/KU-ACTIVE#138]
In the dropdown navbar, it shows some menus that should be authenticated such as "Manage Your Activity!", "Calendar". It correctly redirect to the login page, but in my opinion, it should not be shown.

<img width="874" alt="Screenshot 2566-11-25 at 22 44 01" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/111471511/1c8320dc-2094-42ca-b3d7-1ca99362ee83">

**Comment by Nantawat6510545543** [comment]
I want to show all the users so that they can know what the website has to offer.

**Comment by J-Jullaphong** [comment]
If so, then why does the main navbar don't have some of those? I have to resize my screen to get the dropdown navbar to know what your website can offer?

**Comment by Kongkawee** [comment]
Because the purpose of the dropdown is to handle the size problem of the screen resolution, if we put things in the nav bar, it would expand into a large ugly nav bar. Sorry for the inconvenience.
