### ISSUE TITLE
I can't search my friend lists.

### ISSUE THREAD

**Issue by Pichayanon** [Nantawat6510545543/KU-ACTIVE#139]
I specifically search for my friend's name but it still shows other friends.

<img width="1056" alt="KU-Active" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/115008962/362469a4-93fa-45c4-ad80-e1cf9765c8fe">

**Comment by Nantawat6510545543** [comment]
You don't show your URL. How do I know that you did not forget to enter?

**Comment by Pichayanon** [comment]
I search Kongkawee, Why show all?

<img width="1708" alt="ภาพถ่ายหน้าจอ 2566-11-26 เวลา 00 27 58" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/115008962/cd1a9ffc-d5f2-48c6-933e-c3bdf09e4528">

**Comment by CondricNay** [comment]
Fixed.
