### ISSUE TITLE
I got friend request instead of sending friend request

### ISSUE THREAD

**Issue by Nuafah** [Nantawat6510545543/KU-ACTIVE#140]
I tried adding my friend on your website the first time it was working correctly but when I deleted that friend and sent a friend request to that person again I got the friend request instead of sending it to my friend.

The picture shows my request. but Pichayanon didn't add me, I added him
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/115055014/d0893150-e74c-49e2-bba1-14f977fae835)

**Comment by CondricNay** [comment]
It's fixed now, please try again.
