### ISSUE TITLE
I search with exact date and select time, time does not affect the result.

### ISSUE THREAD

**Issue by Pichayanon** [Nantawat6510545543/KU-ACTIVE#141]
In search with exact date, your application let user select time but time does not affect the result.
I'm not sure if you want to be able to search only for date, why would you include time?

<img width="1134" alt="ภาพถ่ายหน้าจอ 2566-11-25 เวลา 23 44 17" src="https://github.com/Nantawat6510545543/KU-ACTIVE/assets/115008962/8dfa0018-ee33-4050-bdc3-97f53fc4d5fa">

**Comment by CondricNay** [comment]
It depends on your browser, some browser support selecting both date and time, while other support only date
so we make it only choose by date
