### ISSUE TITLE
The name in calendar doesn't match the name of the activity (it got changed).

### ISSUE THREAD

**Issue by MeHappyLucky** [Nantawat6510545543/KU-ACTIVE#142]
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/ae17bd95-6ec0-4d9e-a476-fda77021dad6)
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/041185dd-a22a-4fdb-a68e-b9d8b74f2a9f)

**Comment by Kongkawee** [comment]
I have spotted this problem for a while and found out that it's beyond my ability to handle (it's on the user's side), so I've planned to write the user disclaimer for it. By the way, I'm glad you noticed that :)

**Comment by CondricNay** [comment]
Fixed. (hopefully)
