### ISSUE TITLE
Participant limit can be change to a number that doesn't make sense.

### ISSUE THREAD

**Issue by MeHappyLucky** [Nantawat6510545543/KU-ACTIVE#144]
I think participants limit should be unchangeable after the publicized date, or it should not be able to be lower than the participants that already participated.

![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/a9c17480-d699-4074-809b-b64c1a065a2f)

**Comment by Nantawat6510545543** [comment]
Should be increased or decreased. Activities are subject to change at any time.
