### ISSUE TITLE
Categories got reset during editing.

### ISSUE THREAD

**Issue by MeHappyLucky** [Nantawat6510545543/KU-ACTIVE#145]
I think the categories should still be checked. It would be a pain to check all of them on every edit.

### Before Editing:
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/705080fd-669a-4dd7-b141-5317e8d647be)
### During Editing:
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/114503839/7052e8b5-a6b4-4a78-bb46-808e79864a90)

**Comment by CondricNay** [comment]
Already fixed
