### ISSUE TITLE
Profile Picture easier option

### ISSUE THREAD

**Issue by CondricNay** [Nantawat6510545543/KU-ACTIVE#4]
Easier option, maybe try URLField then use html

use this tag

img src="https://example.com/path/to/your/image.jpg" alt="Image Description"

**Comment by Nantawat6510545543** [comment]
This was a good idea. I put it in iteration 2.

**Comment by Nantawat6510545543** [comment]
This work will continue to be in progress during iteration 3 due to changes in the proposals.

**Comment by Nantawat6510545543** [comment]
This issue is being addressed to enhance security. You can find more details in issue #24.
