### ISSUE TITLE
Implement OAuth-based authentication methods

### ISSUE THREAD

**Issue by CondricNay** [Nantawat6510545543/KU-ACTIVE#9]

**Comment by Nantawat6510545543** [comment]
OAuth-based authentication methods should be automatically configured instead of requiring manual data loading.

**Comment by Nantawat6510545543** [comment]
This issue will be reclassified as 'in progress.'

**Comment by Nantawat6510545543** [comment]
OAuth-based authentication auto setup is functioning correctly, and this issue will be closed.
